repos:
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
    - id: bandit
      args: ["-c", "app_python/pyproject.toml"]
      additional_dependencies: [ "bandit[toml]" ]
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    args: ["--config", "app_python/pyproject.toml"]
- repo: https://github.com/psf/black.git
  rev: 23.7.0
  hooks:
  - id: black
    args: ["--config", "app_python/pyproject.toml"]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--settings-path", "app_python/pyproject.toml"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      exclude: ^k8s/(.*)-chart/
    - id: check-added-large-files
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
- repo: local
  hooks:
    - id: go-unit-tests
      name: run go test s(go test)
      language: system
      entry: bash -c 'cd app_go && exec go test *.go'
      pass_filenames: false
      types: [go]
      files: ^app_go/
- repo: https://github.com/hadolint/hadolint
  rev: v2.12.0
  hooks:
    - id: hadolint
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.4
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
